#!/usr/bin/env bash
#
# Generate beautiful PDF diff using latexdiff
# Inline diff with character-level highlighting (red=deleted, green=added)
#

cd "$(dirname "$0")/.." || exit 1

TAG1="${1:-proposal/v1}"
TAG2="${2:-proposal/v2}"
TMPDIR="/tmp/diff_$$"
OUTDIR="scratch"

mkdir -p "$TMPDIR"
mkdir -p "$OUTDIR/diff_files"

echo "=== Generating diff: $TAG1 -> $TAG2 ==="

# Get list of changed tex files
FILES=$(git diff --name-status -M "$TAG1" "$TAG2" | awk -F'\t' '
/^[RC]/ {print $3}
/^[AM]/ {print $2}
/^D/ {print $2}
' | grep '\.tex$' | sort -u)

IDX=0
for f in $FILES; do
    IDX=$((IDX + 1))
    echo "Processing [$IDX]: $f"

    # Get old and new content
    V1_CONTENT=$(git show "$TAG1:$f" 2>/dev/null || echo "")
    V2_CONTENT=$(git show "$TAG2:$f" 2>/dev/null || echo "")

    if [[ -z "$V1_CONTENT" && -z "$V2_CONTENT" ]]; then
        continue
    fi

    # Write temp files
    echo "$V1_CONTENT" > "$TMPDIR/v1_${IDX}.tex"
    echo "$V2_CONTENT" > "$TMPDIR/v2_${IDX}.tex"

    # Generate latexdiff
    latexdiff --type=TRADITIONAL --subtype=COLOR \
        "$TMPDIR/v1_${IDX}.tex" \
        "$TMPDIR/v2_${IDX}.tex" \
        > "$OUTDIR/diff_files/diff_${IDX}.tex" 2>/dev/null
done

# Build combined PDF
cat > "$OUTDIR/proposal_diff.tex" << MAINLATEX
\documentclass[12pt,a4paper,landscape]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{xcolor}
\usepackage{colortbl}
\usepackage{geometry}
\usepackage{fancyhdr}
\usepackage{ifthen}

\geometry{margin=1cm,landscape}
\pagestyle{fancy}
\fancyhf{}
\fancyhead[L]{\textbf{Proposal Diff: $TAG1 -> $TAG2}}
\fancyhead[R]{\thepage}
\fancyfoot[L]{Generated by scripts/proposal\_diff.sh}

% latexdiff colors (TRADITIONAL style)
\definecolor{diffremove}{RGB}{0.886,0.271,0.271}
\definecolor{diffadd}{RGB}{0.125,0.559,0.125}
\definecolor{diffchg}{RGB}{0.149,0.141,0.912}

\begin{document}

\thispagestyle{empty}
\begin{center}
{\Large \textbf{Proposal Diff Report}}\\[0.5em]
\texttt{$TAG1 $\rightarrow$ $TAG2}\\[0.5em]
\today
\end{center}
\newpage

MAINLATEX

# Add each diff as a section
IDX=0
for f in $FILES; do
    IDX=$((IDX + 1))
    if [[ -f "$OUTDIR/diff_files/diff_${IDX}.tex" ]]; then
        echo "\section*{$f}" >> "$OUTDIR/proposal_diff.tex"
        echo "\input{diff_files/diff_${IDX}.tex}" >> "$OUTDIR/proposal_diff.tex"
        echo "\newpage" >> "$OUTDIR/proposal_diff.tex"
    fi
done

echo "\end{document}" >> "$OUTDIR/proposal_diff.tex"

echo ""
echo "=== Compiling PDF ==="
pdflatex -interaction=nonstopmode -output-directory="$OUTDIR" "$OUTDIR/proposal_diff.tex" > /dev/null 2>&1

echo ""
echo "=== Done! Output: $OUTDIR/proposal_diff.pdf ==="
ls -la "$OUTDIR/proposal_diff.pdf" 2>/dev/null || echo "PDF not generated"

rm -rf "$TMPDIR"
