#!/usr/bin/env python3
"""
Generate side-by-side diff PDF (Monaco/VS Code style)
Uses LaTeX directly for PDF output
"""

import subprocess
import sys
import os
import re
from pathlib import Path

def get_git_content(tag, path):
    """Get file content from a git tag"""
    try:
        result = subprocess.run(
            ['git', 'show', f'{tag}:{path}'],
            capture_output=True, text=True, check=True
        )
        return result.stdout
    except:
        return None

def escape_latex(text):
    """Escape special LaTeX characters for verbatim display"""
    if not text:
        return ""
    result = []
    i = 0
    while i < len(text):
        c = text[i]
        if c == '\\':
            result.append(r'\textbackslash{}')
        elif c == '{':
            result.append(r'\{')
        elif c == '}':
            result.append(r'\}')
        elif c == '&':
            result.append(r'\&')
        elif c == '%':
            result.append(r'\%')
        elif c == '$':
            result.append(r'\$')
        elif c == '#':
            result.append(r'\#')
        elif c == '_':
            result.append(r'\_')
        elif c == '~':
            result.append(r'\textasciitilde{}')
        elif c == '^':
            result.append(r'\textasciicircum{}')
        elif c == '\t':
            result.append('    ')
        elif c == '\n':
            result.append(' ')
        else:
            result.append(c)
        i += 1
    return ''.join(result)

def generate_diff_latex(tag1, tag2, outdir):
    """Generate side-by-side diff as LaTeX"""
    print(f"=== Generating side-by-side diff: {tag1} -> {tag2} ===")

    # Get changed tex files
    result = subprocess.run(
        ['git', 'diff', '--name-status', '-M', tag1, tag2],
        capture_output=True, text=True
    )

    files = []
    for line in result.stdout.strip().split('\n'):
        if not line:
            continue
        parts = line.split('\t')
        status = parts[0]
        if status.startswith('R'):
            old_path = parts[1]
            new_path = parts[2]
            if new_path.endswith('.tex'):
                files.append(('R', old_path, new_path))
        elif status in ('A', 'M'):
            path = parts[1]
            if path.endswith('.tex'):
                files.append((status, path, path))
        elif status == 'D':
            path = parts[1]
            if path.endswith('.tex'):
                files.append((status, path, None))

    # Build LaTeX document
    latex = []
    latex.append(r'\documentclass[9pt,a4paper,landscape]{article}')
    latex.append(r'\usepackage[T1]{fontenc}')
    latex.append(r'\usepackage[utf8]{inputenc}')
    latex.append(r'\usepackage{xcolor}')
    latex.append(r'\usepackage{colortbl}')
    latex.append(r'\usepackage{geometry}')
    latex.append(r'\usepackage{fancyhdr}')
    latex.append(r'\usepackage{longtable}')
    latex.append(r'\usepackage{ifthen}')
    latex.append(r'\usepackage{parnotes}')
    latex.append(r'\usepackage{seqsplit}')

    latex.append(r'\geometry{margin=0.5cm,landscape}')
    latex.append(r'\pagestyle{fancy}')
    latex.append(r'\fancyhf{}')
    latex.append(r'\fancyhead[L]{\textbf{Proposal Diff: ' + f'{tag1} $\\rightarrow$ {tag2}' + r'}}')
    latex.append(r'\fancyhead[R]{\thepage}')
    latex.append(r'\fancyfoot[L]{Generated by scripts/sidebydiff.py}')

    latex.append(r'\definecolor{addbg}{RGB}{19,58,30}')
    latex.append(r'\definecolor{delbg}{RGB}{58,30,30}')
    latex.append(r'\definecolor{addfg}{RGB}{78,201,176}')
    latex.append(r'\definecolor{delfg}{RGB}{241,76,76}')
    latex.append(r'\definecolor{linebg}{RGB}{30,30,30}')
    latex.append(r'\definecolor{linefg}{RGB}{212,212,212}')
    latex.append(r'\definecolor{headerbg}{RGB}{45,45,45}')
    latex.append(r'\definecolor{headerfg}{RGB}{86,156,214}')

    latex.append(r'\parindent=0pt')
    latex.append(r'\parskip=0pt')
    latex.append(r'\setlength{\LTleft}{0pt}')
    latex.append(r'\setlength{\LTright}{0pt}')

    latex.append(r'\begin{document}')
    latex.append(r'\thispagestyle{empty}')
    latex.append(r'{\LARGE\textbf{Proposal Diff Report}\\[0.5em]}')
    latex.append(r'{\texttt{' + f'{tag1} $\\rightarrow$ {tag2}' + r'}}\\[0.5em]')
    latex.append(r'{\large\\today}\\[1em]')
    latex.append(r'\newpage')

    for status, old_path, new_path in files:
        print(f"Processing: {new_path or old_path}")

        old_content = get_git_content(tag1, old_path) if old_path else ""
        new_content = get_git_content(tag2, new_path) if new_path else ""

        if not old_content and not new_content:
            continue

        old_lines = old_content.split('\n') if old_content else []
        new_lines = new_content.split('\n') if new_content else []

        diff_lines = compute_diff(old_lines, new_lines)

        latex.append(r'\section*{' + escape_latex(new_path or old_path) + r'}')
        latex.append(r'\begin{longtable}{|p{0.45\linewidth}|p{0.45\linewidth}|}')
        latex.append(r'\hline')
        latex.append(r'\multicolumn{1}{|c|}{\textbf{Old (' + escape_latex(tag1) + r')}} & \multicolumn{1}{c|}{\textbf{New (' + escape_latex(tag2) + r')}} \\')
        latex.append(r'\hline')
        latex.append(r'\hline')
        latex.append(r'\endfirsthead')
        latex.append(r'\hline')
        latex.append(r'\multicolumn{1}{|c|}{\textbf{Old (' + escape_latex(tag1) + r')}} & \multicolumn{1}{c|}{\textbf{New (' + escape_latex(tag2) + r')}} \\')
        latex.append(r'\hline')
        latex.append(r'\endhead')

        # Process diff lines
        old_buffer = []
        new_buffer = []
        flush = False

        def flush_buffers():
            out = []
            if old_buffer or new_buffer:
                # Left side
                if old_buffer:
                    for line_type, content in old_buffer:
                        if line_type == 'deleted':
                            out.append(r'{\color{delfg}\texttt{' + escape_latex(content) + r'}}')
                        else:
                            out.append(r'{\color{linefg}\texttt{' + escape_latex(content) + r'}}')
                else:
                    out.append(r'~')
                out.append(r'\\')

                # Right side
                if new_buffer:
                    for line_type, content in new_buffer:
                        if line_type == 'added':
                            out.append(r'{\color{addfg}\texttt{' + escape_latex(content) + r'}}')
                        else:
                            out.append(r'{\color{linefg}\texttt{' + escape_latex(content) + r'}}')
                else:
                    out.append(r'~')
                out.append(r'\\')
                out.append(r'\hline')
            return out

        for line_info in diff_lines:
            if line_info[0] == 'deleted':
                if old_buffer and new_buffer:
                    latex.extend(flush_buffers())
                    old_buffer = []
                    new_buffer = []
                old_buffer.append(('deleted', line_info[2]))
            elif line_info[0] == 'added':
                if old_buffer and new_buffer:
                    latex.extend(flush_buffers())
                    old_buffer = []
                    new_buffer = []
                new_buffer.append(('added', line_info[2]))
            else:
                if old_buffer or new_buffer:
                    latex.extend(flush_buffers())
                    old_buffer = []
                    new_buffer = []
                old_buffer.append(('unchanged', line_info[2]))
                new_buffer.append(('unchanged', line_info[2]))

        if old_buffer or new_buffer:
            latex.extend(flush_buffers())

        latex.append(r'\end{longtable}')
        latex.append(r'\newpage')

    latex.append(r'\end{document}')

    # Write LaTeX
    tex_path = os.path.join(outdir, 'proposal_diff.tex')
    with open(tex_path, 'w') as f:
        f.write('\n'.join(latex))

    print(f"LaTeX generated: {tex_path}")
    return tex_path

def compute_diff(old_lines, new_lines):
    """Compute line-by-line diff between two lists of lines"""
    result = []
    old_len, new_len = len(old_lines), len(new_lines)
    i = j = 0

    lcs = compute_lcs(old_lines, new_lines)
    lcs_idx = 0

    while i < old_len or j < new_len:
        if lcs_idx < len(lcs) and i < old_len and j < new_len:
            if old_lines[i] == lcs[lcs_idx] and new_lines[j] == lcs[lcs_idx]:
                result.append(('unchanged', i+1, old_lines[i]))
                i += 1
                j += 1
                lcs_idx += 1
            elif i < old_len and old_lines[i] != lcs[lcs_idx]:
                result.append(('deleted', i+1, old_lines[i]))
                i += 1
            elif j < new_len and new_lines[j] != lcs[lcs_idx]:
                result.append(('added', j+1, new_lines[j]))
                j += 1
        else:
            while i < old_len:
                result.append(('deleted', i+1, old_lines[i]))
                i += 1
            while j < new_len:
                result.append(('added', j+1, new_lines[j]))
                j += 1

    return result

def compute_lcs(a, b):
    """Compute Longest Common Subsequence"""
    m, n = len(a), len(b)
    dp = [[0] * (n + 1) for _ in range(m + 1)]
    for i in range(1, m + 1):
        for j in range(1, n + 1):
            if a[i-1] == b[j-1]:
                dp[i][j] = dp[i-1][j-1] + 1
            else:
                dp[i][j] = max(dp[i-1][j], dp[i][j-1])

    lcs = []
    i, j = m, n
    while i > 0 and j > 0:
        if a[i-1] == b[j-1]:
            lcs.insert(0, a[i-1])
            i -= 1
            j -= 1
        elif dp[i-1][j] > dp[i][j-1]:
            i -= 1
        else:
            j -= 1
    return lcs

def latex_to_pdf(tex_path, outdir):
    """Compile LaTeX to PDF"""
    pdf_path = os.path.join(outdir, 'proposal_diff.pdf')

    try:
        # Compile twice for cross-references
        subprocess.run([
            'pdflatex', '-interaction=nonstopmode',
            f'-output-directory={outdir}', tex_path
        ], capture_output=True, check=True)

        # Move generated PDF to expected location
        generated_pdf = os.path.join(outdir, 'proposal_diff.pdf')
        if os.path.exists(generated_pdf):
            print(f"PDF generated: {generated_pdf}")
            return generated_pdf
    except subprocess.CalledProcessError as e:
        print(f"Error compiling LaTeX: {e}")
        return None

    return None

def main():
    tag1 = sys.argv[1] if len(sys.argv) > 1 else 'proposal/v1'
    tag2 = sys.argv[2] if len(sys.argv) > 2 else 'proposal/v2'
    outdir = sys.argv[3] if len(sys.argv) > 3 else 'scratch'

    os.makedirs(outdir, exist_ok=True)

    tex_path = generate_diff_latex(tag1, tag2, outdir)
    pdf_path = latex_to_pdf(tex_path, outdir)

    if pdf_path:
        size = os.path.getsize(pdf_path)
        print(f"=== Done! Output: {pdf_path} ({size} bytes) ===")
    else:
        print("=== LaTeX generated, but PDF compilation failed ===")

if __name__ == '__main__':
    main()
